var addPoolResults = function (theTournament) {
  let aSport = theTournament.findSport('Netball')
  aSport.addPoolResult('Australia', 'Jamaica', 72, 51)
  aSport.addPoolResult('Australia', 'South Africa', 60, 38)
  aSport.addPoolResult('Australia', 'Northern Ireland', 94, 26)
  aSport.addPoolResult('Australia', 'Barbados', 79, 24)
  aSport.addPoolResult('Australia', 'Fiji',108, 23)
  aSport.addPoolResult('Jamaica', 'South Africa', 57, 46)
  aSport.addPoolResult('Jamaica', 'Northern Ireland', 79, 41)
  aSport.addPoolResult('Jamaica', 'Barbados', 76, 32)
  aSport.addPoolResult('Jamaica', 'Fiji', 88, 30)
  aSport.addPoolResult('South Africa', 'Northern Ireland', 49, 35)
  aSport.addPoolResult('South Africa', 'Barbados', 85, 25)
  aSport.addPoolResult('South Africa', 'Fiji', 92, 28)
  aSport.addPoolResult('Northern Ireland', 'Barbados', 49, 39)
  aSport.addPoolResult('Northern Ireland', 'Fiji', 73, 46)
  aSport.addPoolResult('Barbados', 'Fiji', 65, 44)

  aSport.addPoolResult('England', 'New Zealand', 54, 45)
  aSport.addPoolResult('England', 'Uganda', 55, 49)
  aSport.addPoolResult('England', 'Malawi', 74, 49)
  aSport.addPoolResult('England', 'Scotland', 74, 28)
  aSport.addPoolResult('England', 'Wales', 85, 31)
  aSport.addPoolResult('New Zealand', 'Uganda', 64, 51)
  aSport.addPoolResult('New Zealand', 'Malawi', 53, 57)
  aSport.addPoolResult('New Zealand', 'Scotland', 60, 29)
  aSport.addPoolResult('New Zealand', 'Wales', 70, 44)
  aSport.addPoolResult('Uganda', 'Malawi', 54, 52)
  aSport.addPoolResult('Uganda', 'Scotland', 57, 37)
  aSport.addPoolResult('Uganda', 'Wales', 76, 40)
  aSport.addPoolResult('Malawi', 'Scotland', 51, 50)
  aSport.addPoolResult('Malawi', 'Wales', 68, 53)
  aSport.addPoolResult('Scotland', 'Wales', 51, 47)
}
